env:
  browser: true
  es6: true

extends:
  - airbnb-base
  - plugin:jest/recommended

plugins:
  - jest

parserOptions:
  ecmaVersion: 2020

rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle:
    - error
    - allow:
        - __filename
        - __dirname
